### PR TITLE
Java code for Matrix Inversion

### PR DESCRIPTION
**Pull request by sushant-sinha**
I used Java for matrix inversion: which takes variable 'n' and matrix elements as input and returns the inverted matrix as output.

### CODE REVIEW

**Comment by Astrodevil** [comment]
mention your issue number

**Comment by sushant-sinha** [comment]
I raised a new issue #235.

I tried using the Gauss Jordan method but wasn't able to complete it. But the program still had the comment (which was misleading). So I removed it in Matrix inversion 1.

**Comment by sushant-sinha** [comment]
@Astrodevil @subh-chaturvedi Can you please let me know what specifically we have to do to get the hacktoberfest-accepted label?

**Comment by Astrodevil** [comment]
You have to mention in description that this pr/issue is for hacktoberfest if applicable maintainer will add hacktoberfest-accepted tag

**Comment by sushant-sinha** [comment]
Can you add it now as it's my first fest and wasn't aware of this.

From now on I will add this in my description.

**Pull request merged**
