### PR TITLE
Word counter

### PR DESCRIPTION
**Pull request by arpitbaheti2002**
This is a C++ program that counts the number of words in a sentence entered by the user.

### CODE REVIEW

**Comment by Astrodevil** [comment]
@arpitbaheti2002 Please mention issue if closed by this PR

**Comment by arpitbaheti2002** [comment]
I don't see any issue I can link with my contribution. Should I create one and link it?
I am a beginner and still struggling with understanding open source. Sorry if I understood you wrong. Hoping for your guidance on this one.

**Comment by arpitbaheti2002** [comment]
Issue #128 can be linked with this contribution.

**Comment by Astrodevil** [comment]
This is not good, that person raises issue 1st, please don't repeat this. Create Issue if assigned then make pr.

**Comment by arpitbaheti2002** [comment]
Extremely sorry, I did not have any idea about this. I Won't repeat it next time. 
I am creating an issue, and follow the process you asked for. Thank You.

**Pull request merged**
