### PR TITLE
Added 2 programs under Bit-Manipulation from HackerRank

### PR DESCRIPTION
**Pull request by spyd3r-byte**
Please provide the tag of hacktoberfest-accepted :)

### CODE REVIEW

**Comment by spyd3r-byte** [comment]
@Astrodevil Please Review : )

**Comment by Astrodevil** [comment]
Please mention issue no.

**Comment by spyd3r-byte** [comment]
@Astrodevil Added ✅ ✔️

**Comment by Astrodevil** [comment]
> 
> 
> Compare it with updated repo and move these files accordingly @spyd3r-byte

Move your both files inside DSA/DSA-CPP/...   there is already a folder of bitmanipulation/questions

**Pull request closed without merging**
