### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by bsprogrammerpython**
I have uploaded my own remainder to take a break

### CODE REVIEW

**Comment by Astrodevil** [comment]
mention issue no.

**Comment by bsprogrammerpython** [comment]
Issue no. 103

**Comment by Astrodevil** [comment]
You mention PR no.

**Comment by Astrodevil** [comment]
You just uploaded program files, It looks like some script or project files. Please move this in respective folder of repo, also attach instruction files.

**Pull request closed without merging**
