### PR TITLE
Added 2 Python Projects made using MoviePy Library

### PR DESCRIPTION
**Pull request by kahtras665**
**Hey there! @Astrodevil**

I've added this pull request as I've made changes to the code base and would like them to get merged to the actual repository.
I am mentioning the changes I've made:-

1. I have added a new folder 'MoviePy Projects' inside the Python folder.
2. Inside that folder, I have added two projects made using the MoviePy library.
3. The two projects are:-
    - **Video to Audio (mp4 to mp3)** -> It is a python script which converts video files into audio files.
    - **Video to GIF** -> It is a python script which converts video files into gif files.
4. I would like to also mention that I've added sample video file for the user to input as well as a sample output file in both the projects.
5. Lastly I would also like to mention that I have added a Readme.md file in both the Projects listing what the program does.

Therefore, I would request you to kindly accept my pull request and merge it with the main repository.

### CODE REVIEW

**Comment by kahtras665** [comment]
@Astrodevil 
This pull request is made with reference to Issue #17

**Comment by subh-chaturvedi** [comment]
Add this project to Python/Project directory instead of the Python directory.

**Comment by kahtras665** [comment]
> Add this project to Python/Project directory instead of the Python directory.

Okay!
I've made the changes and I've added the MoviePy Projects folder to Python/Project directory instead of the Python directory.

**Review by Astrodevil — APPROVED** [review]
looking good

**Pull request merged**
