### PR TITLE
Added some files which closes 4 issues

### PR DESCRIPTION
**Pull request by tausiq2003**
Please merge those
Hi there, I have contributed 4 files which closes 4 issues and deleted
helloworld .c and helloworld.py and printf.c because they may be
reported as spam.
Hope you will like my contribution and please merge pr.
closing #256 #254 #176 #193

### CODE REVIEW

**Comment by tausiq2003** [comment]
Bro please merge 🥺

**Comment by tausiq2003** [comment]
Please merge this @Astrodevil

**Comment by tausiq2003** [comment]
I think you will

**Comment by Astrodevil** [comment]
Put diamond pattern problems in pattern folder inside C++, and don't delete any file, even basic one

**Comment by tausiq2003** [comment]
ok

**Comment by tausiq2003** [comment]
sir I am in problem can't retrieve it

**Comment by Astrodevil** [comment]
At least put your diamond pattern programs in mentioned folder

**Comment by tausiq2003** [comment]
Yeah I will review and do

**Comment by tausiq2003** [comment]
Please check

**Comment by tausiq2003** [comment]
@Astrodevil Can you now merge

**Comment by tausiq2003** [comment]
thanks bro

**Pull request merged**
