### PR TITLE
Create web_scraping.ipynb

### PR DESCRIPTION
**Pull request by abhishekkumar11724**
this is simple web scraping illustration for the new learners.
I had used simple and very basic step to illustrate the steps.
for more instructions, open the file and start reading form the top.

### CODE REVIEW

**Comment by abhishekkumar11724** [comment]
issue no. #164

**Comment by Astrodevil** [comment]
Is it count under project or utility? @siphyshu Please let me Know

**Comment by abhishekkumar11724** [comment]
sir its a beginner project for learners.

**Comment by siphyshu** [comment]
> Is it count under project or utility? @siphyshu Please let me Know 

I think this would come under a project.

**Pull request merged**
