### PR TITLE
Added Codes for multiple containers of STL

### PR DESCRIPTION
**Pull request by Geek-Tekina**
Kindly Merge The PR sir. I have successfully added programs for different containers of Standard Template Library in C++ (including 2-d Vector , Priority_Queue etc).

### CODE REVIEW

**Comment by Astrodevil** [comment]
Good Work! keeps Contributing

**Comment by Geek-Tekina** [comment]
Thank You Sir. Happy Contributing with you.

**Comment by Geek-Tekina** [comment]
Sir But on hactoberfest dashboard , it is showing 0 pr. 
I have to do something to update that?

**Comment by Geek-Tekina** [comment]
> > Sir But on hactoberfest dashboard , it is showing 0 pr. I have to do something to update that?
> 
> Check now
sir it is showing in progress

**Comment by Astrodevil** [comment]
> 
> 
> > > Sir But on hactoberfest dashboard , it is showing 0 pr. I have to do something to update that?
> > 
> > 
> > Check now
> > sir it is showing in progress

No issue it will get updated🙌🏼

**Comment by Geek-Tekina** [comment]
It is showing matures in 14 days . What does this mean sir?
please explain!!
#begineer

**Comment by Geek-Tekina** [comment]
Okay Thanku for guiding.

**Comment by Astrodevil** [comment]
> 
> 
> It is showing matures in 14 days . What does this mean sir? please explain!! #begineer

That's the time period for PR review, maintainers can change tags if done by mistake

**Pull request merged**
