### PR TITLE
Added some Algorithms

### PR DESCRIPTION
**Pull request by ArpitaGupta4086**
@Astrodevil Please review

### CODE REVIEW

**Comment by Astrodevil** [comment]
@ArpitaGupta4086 Did you make any issue before this PR? if yes mention it.

**Comment by ArpitaGupta4086** [comment]
@Astrodevil No, I did not. Shall I create one now?

**Comment by Astrodevil** [comment]
> @Astrodevil No, I did not. Shall I create one now?

From next time create Issue and get that assigned to make PR

**Comment by ArpitaGupta4086** [comment]
> > @Astrodevil No, I did not. Shall I create one now?
> 
> From next time create Issue and get that assigned to make PR is this for hacktoberfest?

Okay I'll make sure I do that from the next time. Yes, for Hacktoberfest.

**Pull request merged**
