### PR TITLE
Added Data Structure in Java language 

### PR DESCRIPTION
**Pull request by sunnybhagwat35**
Added programs of  Data Structure in Java language 
topics are:
1)Linked List
  -Singly Linked List
  -Doubly Linked List
  -Circular Linked List
Stack 
  -Using array
  -Using a linked list
Queue
Tree
  -Binary Tree
  -Binary Search Tree
Heap
  -Binary Heap

### CODE REVIEW

**Comment by Astrodevil** [comment]
mention issue no. that is assigned to you

**Comment by sunnybhagwat35** [comment]
> Looking good, Nice work

Thank you😁, btw can you add hacktoberfest accepted label now

**Comment by sunnybhagwat35** [comment]
Why my PR is not in completed state in hacktoberfest site..?

**Comment by Astrodevil** [comment]
> 
> 
> Why my PR is not in completed state in hacktoberfest site..?

If saying matured in 14 days. That's the review period. No problem

**Comment by sunnybhagwat35** [comment]
Oh got it thank you man!

**Pull request merged**
