### PR TITLE
Added Basic Python Projects

### PR DESCRIPTION
**Pull request by ssahibsingh**
I have added Some basic Python Projects.
Issue No. #52

### CODE REVIEW

**Comment by Astrodevil** [comment]
@siphyshu Will you please review and instruct this or other PR related to python projects to be added in project or utilies folder.

**Comment by siphyshu** [comment]
> @siphyshu Will you please review and instruct this or other PR related to python projects to be added in project or utilities folder.

Okay, I will review this PR now, and other ones later when I get time.

**Comment by siphyshu** [comment]
Hey @ssahibsingh, 
These would be better suitable under the [Python/Utility/](https://github.com/Astrodevil/Programming-Basics/tree/main/Python/Utility) category, so please move it there.
Also add a .py script along with the .ipynb notebooks for each of the utilities.

You can look into taking an arguement from the command line for Phone Number Details script using `sys.argv`

**Comment by ssahibsingh** [comment]
@siphyshu I have made all desired changes. Now, Take a look.

**Comment by siphyshu** [comment]
> @siphyshu I have made all desired changes. Now, Take a look.

Perfect! @Astrodevil ready for merge.

**Pull request merged**
