### PR TITLE
Add files 

### PR DESCRIPTION
**Pull request by Rimjhim20**
hey @Astrodevil .
I have added some cpp pdfs for resources.
please merge those pdfs.
Thanks in advance.

### CODE REVIEW

**Comment by Astrodevil** [comment]
@Rimjhim20 Add pdf resources in directory like "Free-resources/C++/pdfs/put your all pdfs"

**Comment by Rimjhim20** [comment]
Ok sure. thank you 🙂

**Comment by Rimjhim20** [comment]
hey @Astrodevil  yes this is for hacktoberfest. I made changes accordingly so now plz merge this.
Thank you.

**Comment by Astrodevil** [comment]
> 
> 
> hey @Astrodevil yes this is for hacktoberfest. I made changes accordingly so now plz merge this. Thank you.

Everything is fine, but it looks like you put file name .pdf.pdf in hurry. let me know if any problem arises due to this.

**Comment by Rimjhim20** [comment]
No it's will not create any issue.

**Comment by Rimjhim20** [comment]
It automatically changed via uploading in . Pdf. So kindly ignore. All pdf
are working fine I guess.

**Comment by Rimjhim20** [comment]
Thanks 😊

**Pull request merged**
