### PR TITLE
simple-tic-tac-toe

### PR DESCRIPTION
**Pull request by Shubham-10-pro**

### CODE REVIEW

**Comment by Shubham-10-pro** [comment]
HI beginner  here.... when I was just starting to program making a Tic tac toe was really fun way to learn for me.. SO i may help other newbie like me to develop interest in programming even more..

**Comment by Astrodevil** [comment]
mention issue no. if assigned !

**Comment by Shubham-10-pro** [comment]
What is issue no? I have just started and dont know most of the thing.(Pardon me if I had told something dumb)

**Comment by Astrodevil** [comment]
> 
> 
> What is issue no? I have just started and dont know most of the thing.(Pardon me if I had told something dumb)

I am not merging this PULL REQUEST for now. Because someone else is already assigned for this.    Please create a new issue and mention changes you want to make.   If issue gets assigned to you, then make PULL REQUEST

**Comment by Shubham-10-pro** [comment]
oh.. thanks for letting me know... I will try

**Pull request closed without merging**
