### PR TITLE
Python project using selenium

### PR DESCRIPTION
**Pull request by saisumanthkumar**
Added project file
Added docs folder

### CODE REVIEW

**Comment by Astrodevil** [comment]
All good. just one thing! Did You add tools? and setup instructions?

**Comment by saisumanthkumar** [comment]
I'll add

**Comment by saisumanthkumar** [comment]
@Astrodevil Added addition system Environment instructions

**Comment by saisumanthkumar** [comment]
@Astrodevil Added system requirements

**Review by Astrodevil — COMMENTED** [review]
Great additions

**Pull request merged**
